apiVersion: apps/v1
kind: Deployment
metadata:
  name: numeroaleatorio-deployment
  labels:
    app: numeroaleatorio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: numeroaleatorio
  template:
    metadata:
      labels:
        app: numeroaleatorio
    spec:
      containers:
        - name: numeroaleatorio-container
          image: theduelxpro/atpipelines:v1
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  name: numeroaleatorio-service
  labels:
    app: numeroaleatorio
spec:
  selector:
    app: numeroaleatorio
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP


