name: Secret Demo

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: secret
    env:
        MY_KEY: ${{ secrets.API_KEY }}
    run: echo "API_KEY configurado (valor ocultado)"
