name: Tests

on:
  pull_request: # dispara em PR

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Rodar testes
        run: echo "Rodando testes"
